### ISSUE TITLE
Modify Dependency resolvePath to use try requireResolvePath first when path does not start with "."

### ISSUE THREAD

**Issue by philidem** [raptorjs/optimizer#39]
PSEUDO CODE:
- If path starts with ".", resolve as relative path
- Otherwise:
    - Try using requireResolvePath
    - If requireResolvePath fails then try resolve as relative path
    - If still not resolved, then throw error

**Comment by philidem** [comment]
A fix for this will also resolve https://github.com/raptorjs/optimizer-less/issues/3

**Comment by patrick-steele-idem** [comment]
Closing issue as changes have been merged in.
